/* Generated by wayland-scanner 1.16.0 */

/*
 * Copyright (c) 2012, Intel Corporation.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message ias_mode_requests[] = {
	{ "add", "", types + 0 },
};

WL_EXPORT const struct wl_interface ias_mode_interface = {
	"ias_mode", 1,
	1, ias_mode_requests,
	0, NULL,
};

static const struct wl_message ias_crtc_requests[] = {
	{ "set_mode", "u", types + 0 },
	{ "set_gamma", "uuu", types + 0 },
	{ "set_contrast", "uuu", types + 0 },
	{ "set_brightness", "uuu", types + 0 },
	{ "set_content_protection", "u", types + 0 },
};

static const struct wl_message ias_crtc_events[] = {
	{ "mode", "uuuu", types + 0 },
	{ "gamma", "uuu", types + 0 },
	{ "contrast", "uuu", types + 0 },
	{ "brightness", "uuu", types + 0 },
	{ "id", "u", types + 0 },
	{ "content_protection_enabled", "", types + 0 },
};

WL_EXPORT const struct wl_interface ias_crtc_interface = {
	"ias_crtc", 1,
	5, ias_crtc_requests,
	6, ias_crtc_events,
};

static const struct wl_message ias_output_requests[] = {
	{ "set_xy", "uu", types + 0 },
	{ "disable", "", types + 0 },
	{ "enable", "", types + 0 },
	{ "scale_to", "uu", types + 0 },
	{ "set_fb_transparency", "u", types + 0 },
};

static const struct wl_message ias_output_events[] = {
	{ "name", "s", types + 0 },
};

WL_EXPORT const struct wl_interface ias_output_interface = {
	"ias_output", 1,
	5, ias_output_requests,
	1, ias_output_events,
};

